apiVersion: v1
kind: Service
metadata:
  name: node-ts
  labels:
    run: node-ts
spec:
  type: NodePort
  ports:
    - nodePort: 30870
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: node-ts
